"""Add new profile fields to User

Revision ID: 02f1203f89b7
Revises: 001_initial
Create Date: 2026-07-29 19:13:25.107997
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '02f1203f89b7'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skills', sa.Text(), nullable=True, comment='Comma-separated list of skills'))
    op.add_column('users', sa.Column('projects', sa.Text(), nullable=True, comment='Comma-separated list of projects'))
    op.add_column('users', sa.Column('learning_style', sa.String(length=50), nullable=True, comment='Learning preference (e.g. visual, auditory, kinesthetic)'))
    op.add_column('users', sa.Column('favourite_topics', sa.Text(), nullable=True, comment='Comma-separated list of favourite topics'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favourite_topics')
    op.drop_column('users', 'learning_style')
    op.drop_column('users', 'projects')
    op.drop_column('users', 'skills')
    # ### end Alembic commands ###
