"""auto

Revision ID: 05824bd3af29
Revises: e3a81f2bc901
Create Date: 2026-07-30 09:20:48.781123
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '05824bd3af29'
down_revision: Union[str, None] = 'e3a81f2bc901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False, comment="e.g. 'keyword', 'classifier', 'conflict_high_stress'"),
    sa.Column('action_taken', sa.String(length=50), nullable=False, comment="e.g. 'resource_injected', 'hard_stop'"),
    sa.Column('resolved', sa.Boolean(), nullable=False, comment='Whether the risk was acknowledged or de-escalated'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_session_id'), 'risk_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_risk_events_user_id'), 'risk_events', ['user_id'], unique=False)
    op.alter_column('emotion_logs', 'text_emotion',
               existing_type=sa.VARCHAR(length=50),
               type_=app.utils.encryption.EncryptedText(),
               existing_nullable=True)
    op.alter_column('emotion_logs', 'voice_emotion',
               existing_type=sa.VARCHAR(length=50),
               type_=app.utils.encryption.EncryptedText(),
               existing_nullable=True)
    op.alter_column('emotion_logs', 'face_emotion',
               existing_type=sa.VARCHAR(length=50),
               type_=app.utils.encryption.EncryptedText(),
               existing_nullable=True)
    op.alter_column('emotion_logs', 'fused_emotion',
               existing_type=sa.VARCHAR(length=50),
               type_=app.utils.encryption.EncryptedText(),
               existing_nullable=False)
    op.add_column('sessions', sa.Column('phase', sa.String(length=50), server_default='check_in', nullable=False))
    op.add_column('sessions', sa.Column('mode', sa.String(length=10), server_default='chat', nullable=False))
    op.alter_column('user_goals', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               comment="Short descriptive title, e.g. 'Learn Data Science'",
               existing_nullable=False)
    op.alter_column('user_goals', 'description',
               existing_type=sa.TEXT(),
               comment='Detailed description of what the user wants to achieve',
               existing_nullable=True)
    op.alter_column('user_goals', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='Category: career, learning, fitness, mental_wellness, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'other'::character varying"))
    op.alter_column('user_goals', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               comment='Lifecycle status: active, paused, completed, abandoned',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('user_goals', 'priority',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Priority score 0.0–1.0 (higher = more important)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('user_goals', 'progress_notes',
               existing_type=sa.TEXT(),
               comment='Rolling notes about progress towards this goal',
               existing_nullable=True)
    op.alter_column('user_goals', 'milestones',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON array of milestone objects: [{title, completed, date}]',
               existing_nullable=True)
    op.alter_column('user_goals', 'source_session_id',
               existing_type=sa.INTEGER(),
               comment='Session where this goal was first detected',
               existing_nullable=True)
    op.alter_column('user_goals', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Arbitrary metadata for extensibility',
               existing_nullable=True)
    op.drop_index(op.f('ix_user_goals_id'), table_name='user_goals')
    op.create_index(op.f('ix_user_goals_status'), 'user_goals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_goals_status'), table_name='user_goals')
    op.create_index(op.f('ix_user_goals_id'), 'user_goals', ['id'], unique=False)
    op.alter_column('user_goals', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Arbitrary metadata for extensibility',
               existing_nullable=True)
    op.alter_column('user_goals', 'source_session_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Session where this goal was first detected',
               existing_nullable=True)
    op.alter_column('user_goals', 'milestones',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON array of milestone objects: [{title, completed, date}]',
               existing_nullable=True)
    op.alter_column('user_goals', 'progress_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Rolling notes about progress towards this goal',
               existing_nullable=True)
    op.alter_column('user_goals', 'priority',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Priority score 0.0–1.0 (higher = more important)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.5'::double precision"))
    op.alter_column('user_goals', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Lifecycle status: active, paused, completed, abandoned',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('user_goals', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Category: career, learning, fitness, mental_wellness, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'other'::character varying"))
    op.alter_column('user_goals', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description of what the user wants to achieve',
               existing_nullable=True)
    op.alter_column('user_goals', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Short descriptive title, e.g. 'Learn Data Science'",
               existing_nullable=False)
    op.drop_column('sessions', 'mode')
    op.drop_column('sessions', 'phase')
    op.alter_column('emotion_logs', 'fused_emotion',
               existing_type=app.utils.encryption.EncryptedText(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('emotion_logs', 'face_emotion',
               existing_type=app.utils.encryption.EncryptedText(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('emotion_logs', 'voice_emotion',
               existing_type=app.utils.encryption.EncryptedText(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('emotion_logs', 'text_emotion',
               existing_type=app.utils.encryption.EncryptedText(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_risk_events_user_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_session_id'), table_name='risk_events')
    op.drop_table('risk_events')
    # ### end Alembic commands ###
